# This file contains the list of repositories including their unique short name
# (like a namespace) and the base URL to their location.
#
# Every repo listed here MUST have a corresponding entry in the repos.yaml at
# the root of this source repository with the exception of the Helm hosted ones.
sync:
  repos:
    # Helm hosted repositories
    - name: stable
      url: https://kubernetes-charts.storage.googleapis.com
    - name: incubator
      url: https://kubernetes-charts-incubator.storage.googleapis.com
    - name: jfrog
      url: https://charts.jfrog.io
    - name: kremers
      url: https://kremers.github.io
    - name: rimusz
      url: https://charts.rimusz.net
    - name: buildkite
      url: https://buildkite.github.io/charts
    - name: keel
      url: https://charts.keel.sh
    - name: appscode
      url: https://charts.appscode.com/stable/
    - name: gitlab
      url: https://charts.gitlab.io/
    - name: bitnami
      url: https://charts.bitnami.com
    - name: weave-flux
      url: https://weaveworks.github.io/flux/
    - name: jetstack
      url: https://charts.jetstack.io
    - name: ibm-charts
      url: https://raw.githubusercontent.com/IBM/charts/master/repo/stable/
    - name: kanister
      url: https://charts.kanister.io/
    - name: flagger
      url: https://flagger.app
    - name: zammad
      url: https://zammad.github.io
    - name: agones
      url: https://agones.dev/chart/stable
    - name: banzaicloud-stable
      url: https://kubernetes-charts.banzaicloud.com
    - name: kiwigrid
      url: https://kiwigrid.github.io
    - name: elastic
      url: https://helm.elastic.co
    - name: openfaas
      url: https://openfaas.github.io/faas-netes
    - name: odavid
      url: https://odavid.github.io/k8s-helm-charts
    - name: soluto
      url: https://charts.soluto.io
    - name: hephy
      url: https://charts.teamhephy.com
    - name: gabibbo97
      url: https://gabibbo97.github.io/charts/
    - name: presslabs
      url: https://presslabs.github.io/charts
    - name: eventstore
      url: https://eventstore.github.io/EventStore.Charts
    - name: pnnl-miscscripts
      url: https://pnnl-miscscripts.github.io/charts
    - name: ceph-csi
      url: https://ceph.github.io/csi-charts
    - name: reactiveops-stable
      url: https://charts.reactiveops.com/stable
    - name: yourls
      url: https://charts.yourls.org
    - name: hazelcast
      url: https://hazelcast.github.io/charts/
    - name: nginx
      url: https://helm.nginx.com/stable
    - name: cic
      url: https://citrix.github.io/citrix-k8s-ingress-controller/
    - name: zooz
      url: https://zooz.github.io/helm/
    - name: rancher-stable
      url: https://releases.rancher.com/server-charts/stable
    - name: loki
      url: https://grafana.github.io/loki/charts
    - name: microsoft
      url: https://microsoft.github.io/charts/repo
    - name: codecentric
      url: https://codecentric.github.io/helm-charts
    - name: okgolove
      url: https://okgolove.github.io/helm-charts
    - name: dhiatn
      url: https://dhiatn.github.io/helm-kafka-topics-ui
    - name: k8dash
      url: https://herbrandson.github.io/k8dash/helm
    - name: funkypenguin
      url: https://funkypenguin.github.io/helm-charts
    - name: mattermost
      url: https://helm.mattermost.com
    - name: emberstack
      url: https://emberstack.github.io/helm-charts
    # - name: APPUiO
    # Switching to a lowercase name until https://github.com/helm/monocular/issues/626
    # is fixed
    - name: appuio
      url: https://charts.appuio.ch
    - name: gomods
      url: https://athens.blob.core.windows.net/charts
    - name: zentainer
      url: https://charts.zentainer.app
    - name: promitor
      url: https://promitor.azurecr.io/helm/v1/repo
    - name: kir4h
      url: https://kir4h.github.io/charts
    - name: hmdmph
      url: https://hmdmph.github.io/helm-charts
    - name: drgrove
      url: https://drgrove.github.io/charts
    - name: harbor
      url: https://helm.goharbor.io
    - name: appdynamics
      url: https://appdynamics.github.io/appdynamics-charts
    - name: billimek
      url: https://billimek.com/billimek-charts/
    - name: choerodon
      url: https://openchart.choerodon.com.cn/choerodon/c7n
    - name: kedacore
      url: https://kedacore.azureedge.net/helm
    - name: seldon
      url: https://storage.googleapis.com/seldon-charts
    - name: gkarthiks
      url: https://gkarthiks.github.io/helm-charts
    - name: opsdroid
      url: https://helm.opsdroid.dev/
    - name: privatebin
      url: https://privatebin.github.io/helm-chart/
    - name: gresearch
      url: https://g-research.github.io/charts/
    - name: smallstep
      url: https://smallstep.github.io/helm-charts/
    - name: volcano
      url: https://volcano-sh.github.io/charts/
    - name: ory
      url: https://k8s.ory.sh/helm/charts
    - name: cetic
      url: https://cetic.github.io/helm-charts
    - name: qamatic
      url: https://qamatic.github.io/charts
    - name: sstarcher
      url: https://shanestarcher.com/helm-charts/
    - name: lifen
      url: https://honestica.github.io/lifen-charts/
    - name: owkin
      url: https://owkin.github.io/charts
